# Page settings
baseurl = "localhost:1313"
title = "StudentHack V"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params] 
  custom_css = ["css/custom1.css"]

  # Meta
  author = "StudentHack V"
  description = "StudentHack V 2017 - #learn #build #share 10-12 March 2017"
  email = "cristian@hacksoc.com"
  # Navigation
  [params.navigation]
    brand = "StudentHack V"
    home = "Home"
    faq = "FAQ"
    schedule = "Schedule"
    sponsors = "Sponsors"
    location = "Location"
    contact = "Get In Touch"
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = " "
    #  name = " "
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "10-12 March 2017 <br> Manchester, England"
    subtitle = "The epic student hackathon in Manchester <br> & we're making it more accessible than ever."
    url = "#"

  # FAQ section
  [params.faq]
    enable = true
    title = "FAQ"

    [[params.faq.item]]
      title = "Are tickets free?"
      description = "Yes, 100%."
      icon = "icon-wallet"

    [[params.faq.item]]
      title = "Who can get a ticket?"
      description = "All enrolled students over 18 and those who graduated in the last one year."
      icon = "icon-graduation"

    [[params.faq.item]]
      title = "What if I study outside the UK?"
      description = "You are still welcome to join us! However, we cannot sponsor visas."
      icon = "icon-plane"

    [[params.faq.item]]
      title = "I haven't coded much. Should I come?"
      description = "Hackathons are for beginners. Networking with and seeing awesome hackers in action will expose you to a tremendous amount of knowledge. There is an amazing suit of industry experts and mentors that are happy to assist you!"      
      icon = "icon-briefcase"

    [[params.faq.item]]
      title = "What should I bring?"
      description = "Bring your laptop, phone and chargers. Other things to consider: spare clothes, adapters, hardware and a sleeping bag, oh and don't forget your enthusiasm! We are going to provide you with all the food, swag, sleeping rooms and the drinks that you will need."      
      icon = "icon-basket-loaded"

    [[params.faq.item]]
      title = "I don't have a team. Help?"
      description = "Don't let that discourage you ― it is actually part of the fun! You will have 3 new friends by the end of the weekend. A team building session will be organized to help you form teams. We encourage everyone to use Devpost to find teammates."      
      icon = "icon-people"

    [[params.faq.item]]
      title = "What can I expect from StudentHack?"
      description = "An entire weekend of great company, good food and plenty of swag! We'll also have hardware and tons of mentors."      
      icon = "icon-magic-wand"

    [[params.faq.item]]
      title = "Who owns my IP/code/idea?"
      description = "You own all the rights to your intellectual property. We won't claim any right over anything made during this event."      
      icon = "icon-bulb"

    [[params.faq.item]]
      title = "Do you have a code of conduct?"
      description = "Yes! We strictly adhere to the <a href='https://static.mlh.io/docs/mlh-code-of-conduct.pdf'>Major League Hacking Code of Conduct</a>."      
      icon = "icon-book-open"

  # Schedule section
  [params.schedule]
    enable = false 
    title = "Schedule"
    description = "N/A"

    [[params.schedule.item]]
      quote = "N/A"
      person = "N/A"
      img = "person1.jpg"
      alt = "Person1"

  # Sponsors section
  [params.sponsors]
    enable = false
    title = "Sponsors"
    description = "They made it possible!"
    footertext = "We Thank you!"

    [[params.sponsors.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Sponsor"
      subtitle = "Sponsor"

  # Location section
  [params.location]
    enable = true
    map = true
    title = "Location"
    description = "The Landing, Blue, MediaCityUK, M50 2ST, Manchester, UK"  

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Hackers Pre-registerd"
      icon = "icon-briefcase"
      from = 0
      to = 148
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of Code"
      icon = "icon-code"
      from = 0
      to = 343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1337
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Sleepless Hours"
      icon = "icon-power"
      from = 0
      to = 420
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    title = "Get in touch"
    description = "For any question, feedback or sponsorship proposal, feel free to contact us!"
    
    # Available icons: http://simplelineicons.com/

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a> <br> Edited By  <a href="http://hacksoc.com/" target="_blank">HackSoc</a> Dev Team'
