# Page settings
baseurl = "localhost:1313"
title = "StudentHack V"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params] 
  custom_css = ["css/custom1.css"]

  # Meta
  author = "Raul Ignatus"
  description = "StudentHack V website"
  email = "raulignatus@gmail.com"
  # Navigation
  [params.navigation]
    brand = "StudentHack V"
    home = "Home"
    faq = "FAQ"
    schedule = "Schedule"
    sponsors = "Sponsors"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Spring 2017 - Manchester, England"
    subtitle = "The epic student hackathon in Manchester <br> & we're making it more accessible than ever."
    url = "#"

  # FAQ section
  [params.faq]
    enable = true
    title = "FAQ"

    [[params.faq.item]]
      title = "Are tickets free?"
      description = "Yes, 100%."
      icon = "icon-anchor"

    [[params.faq.item]]
      title = "Who can get a ticket?"
      description = "All enrolled students over 18 and those who graduated in the last one year."
      icon = "icon-layers2"

    [[params.faq.item]]
      title = "What if I study outside the UK?"
      description = "You are still welcome to join us! However, we cannot sponsor visas."
      icon = "icon-video2"

    [[params.faq.item]]
      title = "I haven't coded much. Should I come?"
      description = "Hackathons are for beginners. Networking with and seeing awesome hackers in action will expose you to a tremendous amount of knowledge. Amazing suit of industry experts and mentors that are happy to assist you!"      
      icon = "icon-monitor"

    [[params.faq.item]]
      title = "What should I bring?"
      description = "Bring your laptop, phone and chargers. Other things to consider: spare clothes, adapters, hardware and a sleeping bag, oh and don't forget your enthusiasm! We are going to provide you with all food, swag, sleeping rooms and drinks you will need to keep you going."      
      icon = "icon-monitor"

    [[params.faq.item]]
      title = "I don't have a team. Help?"
      description = "Don't let that discourage you ― it is actually part of the fun! You will have 3 new friends by the end of the weekend. A team building session will be organized to help you form teams. We encourage everyone to use Devpost to find teammates."      
      icon = "icon-monitor"

    [[params.faq.item]]
      title = "What can I expect from GreatUniHack?"
      description = "An entire weekend of great company, good food and plenty of swag! We'll also have hardware and tons of mentors."      
      icon = "icon-monitor"

    [[params.faq.item]]
      title = "Who owns my IP/code/idea?"
      description = "You own all the rights to your intellectual property. We won't claim any right over anything made during this event."      
      icon = "icon-monitor"

    [[params.faq.item]]
      title = "Do you have a code of conduct?"
      description = "Yes! We strictly adhere to the <a href='https://static.mlh.io/docs/mlh-code-of-conduct.pdf'>Major League Hacking Code of Conduct</a>."      
      icon = "icon-monitor"

    [[params.faq.item]]
      title = "Wanna Pre-register?"
      description = "Yes! You can doo it right <a href='https://docs.google.com/forms/d/1soQyVObgRUz1TyeQrhe1aGcHU0pZsB99X9UBrrGpuaI/edit'> here</a>." 
      icon = "icon-monitor"

  # Schedule section
  [params.schedule]
    enable = true 
    title = "Schedule"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.schedule.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.schedule.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.schedule.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # Sponsors section
  [params.sponsors]
    enable = true
    title = "Sponsors"
    description = "They made it possible!"

    [[params.sponsors.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Sponsor "
      subtitle = "Sponsor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "

    [[params.about.item]]
      name = ""
      position = ""
      description = ""
      img = ""
      alt = ""
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Hackers Pre-registerd"
      icon = "icon-briefcase"
      from = 0
      to = 148
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of Code"
      icon = "icon-code"
      from = 0
      to = 343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1337
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Sleepless Hours"
      icon = "icon-people"
      from = 0
      to = 420
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "From any stupid question to the perfect feedback, feel free to contact us"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "N/A"],
        ["icon-phone", "N/A"],
        ["icon-envelope", "N/A"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
